{{- if and (eq "nexus" .Values.jxRequirements.repository) .Values.istio.enabled }}
apiVersion: {{ .Values.istio.apiVersion }}
kind: VirtualService
metadata:
  name: chartmuseum
spec:
  gateways:
  - jx-gateway
  hosts:
    - chartmuseum{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: chartmuseum
      weight: 100
{{- end }}