{{- if (eq "bucketrepo" .Values.jxRequirements.repository) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: bucketrepo
spec:
  rules:
  - host: bucketrepo{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: bucketrepo
          servicePort: 80
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
    - bucketrepo{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- if hasKey .Values.jxRequirements.ingress.tls "secretName" }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}