{{- if and (index .Values "docker-registry" "enabled") .Values.istio.enabled }}
apiVersion: {{ .Values.istio.apiVersion }}
kind: VirtualService
metadata:
  name: docker-registry
spec:
  gateways:
  - jx-gateway
  hosts:
    - docker-registry{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: docker-registry
      weight: 100
{{- end }}