{{- if .Values.secrets.chartMuseumPassword }}
apiVersion: v1
data:
  BASIC_AUTH_PASS: {{ .Values.secrets.chartMuseumPassword | b64enc | quote }}
  BASIC_AUTH_USER: {{ .Values.secrets.chartMuseumUsername | default "" | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
    jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
    jenkins.io/foo: bar
  labels:
    jenkins.io/credentials-type: usernamePassword
    release: jenkins-x
  name: jenkins-x-chartmuseum-core
type: Opaque
{{- end }}