versions:
  # TODO update with latest builders version
  builders: latest

# TODO we want to remove exposecontroller at some point
exposer: Ingress

# imported from the global secrets?
secrets:
  tektonBucket: ""
  featureFlagAPIKey: ""
  chartMuseumPassword: ""
  chartMuseumUsername: ""
  pipelineUser:
    username: ""
    email: ""
    token: ""

docker-registry:
  enabled: false

ingress:
  annotations:
#      kubernetes.io/ingress.class: nginx

jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  bootConfigURL: https://github.com/jenkins-x/jenkins-x-boot-config.git
  cluster:
    clusterName: mycluster
    devEnvApprovers:
    - someone
    environmentGitOwner: myorg
    environmentGitPublic: true
    gitKind: github
    gitName: github
    gitPublic: true
    gitServer: https://github.com
    namespace: jx
    project: myproject
    provider: gke
    zone: europe-west1-c
  environments:
  - key: dev
    repository: environment-mycluster-dev
  gitops: true
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: local
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: false
      url: ""
    reports:
      enabled: false
      url: ""
    repository:
      enabled: false
      url: ""
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jenkins-x-versions.git
  webhook: lighthouse
